# Generated by Django 2.2 on 2020-09-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ok_redirects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is active'),
        ),
    ]
