# Generated by Django 2.1.4 on 2020-09-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ok_redirects', '0002_redirect_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='counter',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Counter'),
        ),
        migrations.AddField(
            model_name='redirect',
            name='status_code',
            field=models.PositiveSmallIntegerField(choices=[(301, '301 Moved Permanently'), (302, '302 Found'), (303, '303 See Other'), (307, '307 Temporary Redirect'), (308, '308 Permanent Redirect')], db_index=True, default=301, help_text='The redirect http status code.', verbose_name='Type'),
        ),
    ]
