# Generated by Django 2.1.4 on 2020-12-18 11:22

from django.db import migrations, models
import ok_redirects.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ok_redirects', '0003_auto_20200908_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='languages',
            field=ok_redirects.fields.MultipleChoiceArrayField(base_field=models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Russian'), ('uk', 'Ukraine')], max_length=2), blank=True, default=['en', 'ru', 'uk'], size=None, verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='status_code',
            field=models.PositiveSmallIntegerField(choices=[(301, '301 Moved Permanently'), (302, '302 Found'), (303, '303 See Other'), (307, '307 Temporary Redirect'), (308, '308 Permanent Redirect')], db_index=True, default=301, help_text='The redirect http status code.', verbose_name='Status code'),
        ),
    ]
