# Generated by Django 2.1.4 on 2021-01-12 08:14

from django.db import migrations, models
import ok_redirects.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ok_redirects', '0004_auto_20201218_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='to_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Russian'), ('uk', 'Ukraine')], help_text='Leave blank to redirect to an activated language', max_length=5, verbose_name='to language'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='languages',
            field=ok_redirects.fields.MultipleChoiceArrayField(base_field=models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Russian'), ('uk', 'Ukraine')], max_length=2), blank=True, default=['en', 'ru', 'uk'], size=None, verbose_name='Languages to check redirect'),
        ),
    ]
