# Generated by Django 3.2 on 2022-04-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('ok_redirects', '0005_auto_20210112_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='sites',
            field=models.ManyToManyField(blank=True, to='sites.Site', verbose_name='sites'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='to_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Russian'), ('uk', 'Ukraine')], help_text='Leave blank to redirect to the current language on the site', max_length=5, verbose_name='to language'),
        ),
        migrations.AlterUniqueTogether(
            name='redirect',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='redirect',
            name='site',
        ),
    ]
